apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-with-auto-instrumentation
  namespace: sample-api
  labels:
    app: service-with-auto-instrumentation
spec:
  selector:
    matchLabels:
      app: service-with-auto-instrumentation
  replicas: 1
  template:
    metadata:
      labels:
        app: service-with-auto-instrumentation
      annotations:
        instrumentation.opentelemetry.io/inject-java: "o11y/my-instrumentation"
    spec:
      containers:
      - name: my-api-instrumented
        image: jaegertracing/vertx-create-span:operator-e2e-tests
        ports:
          - containerPort: 8080
            protocol: TCP